### ISSUE TITLE
Canon-iR-ADV_C2020 printer driver does not work

### ISSUE THREAD

**Issue by Marti415** [OpenPrinting/openprinting.github.io#100]
sorrry I'm not sure that I am at the good place and I think that I don't do things in the good way... but I really need help and I don't know how. It's someone who work for Purism who tell me to contact you for help. I try to install a

Canon-iR-ADV_C2020 printer on my Purism laptop (PureOS) but it's impossible! See our email discussion with what Tilix tell me, to understand my need :

« Reading package lists... Done
Construction of the dependency tree      
Reading status information... Done
Note: selection of "cndrvcups-ufr2-uk" instead of
"./cndrvcups-ufr2-uk_3.10-1_amd64.deb".
Some packages cannot be installed. This may mean
that you have asked for the impossible, or, if you are using
the unstable distribution, which some packages don't have yet
were created or have not left Incoming.
The following information should help you resolve the situation:

The following packages contain unsatisfied dependencies:
 cndrvcups-ufr2-uk : Depends: libpng12-0 (>= 1.2.13-4) but it is not
installable

This is found only in older version of Debian linux, ie: not available in PureOS. You need to contact their support and ask for more recent version of the driver.

>                      Depends: cndrvvcups-common (>= 3.40) but it is not
> installable
> E: Impossible to correct problems, faulty packages are in "keep as is" mode.

									This is the other package you haven't installed yet. But you need more recent 
								version of this driver,like I said, so don't install this. »

Please, is it possible to make the driver work with PureOS? It's very important. It's THE only way for me to pass to Linux at my work (not only at my home).

you can contact me at pertinence@riseup.net
Thanks!

**Comment by dkosovic** [comment]
If that Canon iR ADV C2020 has PostScript support (which sometimes is an optional extra on some Canon printers), use the PPD file from the following page:
* https://www.openprinting.org/printer/Canon/Canon-iR-ADV_C2020_2030

See the following page on how to add a print queue using a PPD file :
* https://wiki.debian.org/CUPSPrintQueues#ppd

i.e. :
`sudo lpadmin -p <queue_name> -v <device-uri> -m Canon-iR-ADV_C2020_2030-Postscript-Canon.ppd -E`

**Comment by zdohnal** [comment]
@dkosovic the argument ```-m``` work with model uris from ```lpinfo -m```, not with actual files - ```-P``` is for actual files.

@Marti415 I don't have other advice than @dkosovic - try a similar driver or contact your driver provider for help, which is Canon.

FTR, this repository contains data for openprinting web site - any problems with specific drivers should be reported to the driver provider.

**Comment by HinTak** [comment]
You can download libpng12 from an older distro, and install on your current. It should be installable to your current. (Which has libpng15/libpng16).

**Comment by Marti415** [comment]
Ok so the solution is :lpadmin -p <queue_name> -v <device-uri> -m <PPD_or_everywhere_or_driverless_or_raw> -E
I tried. But Tilix say to me : "bash: queue_name: No such file or folder"
How I can get de queue name? Thanks!

**Comment by zdohnal** [comment]
If something is in <>, it means substitution - the queue name is up to you, it only defines what name the printer will have in print dialogs.
For other subs you can see https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_installation_via_cli_commands .

**Comment by Marti415** [comment]
Tilix say that the name of the queue is "interdit" means "prohibited" in english.

![Capture d’écran de 2023-09-07 16-28-29](https://github.com/OpenPrinting/openprinting.github.io/assets/70961468/07cdc924-7585-49b1-a4dd-a4facab71fbd)

**Comment by dkosovic** [comment]
As you are having so many issues with getting the syntax correct for the command-line, probably simpler for you to use the `system-config-printer` GUI or the https://localhost:631 CUPS web interface to add a printer, your desktop environment might even be able to add printers somewhere in GNOME Control Center.

Also, apologies for conflating things with my initial replay which had the wrong command-line syntax.

**Comment by Marti415** [comment]
As you can see from this screenshot, I used Gnome Control Center. You can see that the Adv-C2020 IR printer is not working. If I connect it with a wire, the printer receives a print command but sends an error signal and doesn't print. And if I print wirelessly, the printer does absolutely nothing. What's more, I want it to be wireless because I'm not in the same office as the printer  x-special/nautilus-clipboard
copy
file:///home/martinfontaine/Images/Capture%20d%E2%80%99%C3%A9cran%20de%202023-10-03%2013-15-32.png

**Comment by Marti415** [comment]
And here's another try using Tilixm and following the instructions on the links you sent me
![Capture d’écran de 2023-10-03 13-28-05](https://github.com/OpenPrinting/openprinting.github.io/assets/70961468/a9d02f7e-eb9f-4ff4-9827-16cc47c114bd)

**Comment by zdohnal** [comment]
I don't understand French, so I can only guess the connection with the printer was terminated - check if IPP port is enabled on the printer (check its web interface - go to your web browser, enter your printer IP and press enter - you may see IPP/AirPrint related settings there somewhere, and if it is enabled, check the port itself via telnet or ncat - search for this on the internet) and then try https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_how_to_find_out_whether_my_printer_is_capable_of_driverless_printing .

FYI here is the manual how to install printer via CUPS web UI - https://docs.fedoraproject.org/en-US/quick-docs/cups-useful-tricks/#_installation_via_cups_web_ui - you can try some generic drivers (PostScript, PDF) as well if IPP Everywhere does not work and you don't have any other driver.

If IPP Everywhere does not work for the printer, contact your printer manufacturer and ask them to provide a driver for your OS.
