### ISSUE TITLE
Add Content Navigation Bar in Right Side of Documentation pages 

### ISSUE THREAD

**Issue by PIYUSHgoyal16** [OpenPrinting/openprinting.github.io#105]
The current documentation layout has no side navigation bar, and looks something like this:
![Screenshot from 2020-10-05 23-41-37](https://user-images.githubusercontent.com/43112419/95116234-59398d00-0764-11eb-95ed-135cfa67ecc8.png)

As the content on the upcoming pages is increasing, navigation to each section is becoming harder. To deal with such a bulkier page, I could break the content into multiple pages, but that would reduce the charm as the user would be just navigating between pages(due to references). Hence, I propose to have a content navigation bar on the right side, utilising the vacant space, helping the reader to have a better experience.

**Comment by iramcdonald** [comment]
Hi,

This navigation sidebar sounds like a good idea to me!

Cheers,
- Ira

**Comment by dheeraj135** [comment]
@PIYUSHgoyal16 I think you want something like this: http://blog.pc.iitmandi.co.in/web-development-for-freshers/. If so, you only need to set ```toc : true``` and probably the ```toc_label```. For reference: https://raw.githubusercontent.com/KamandPrompt/blog/master/_posts/2020-05-25-web-development-for-freshers.md

**Comment by dheeraj135** [comment]
Official documentation for table of contents: https://mmistakes.github.io/minimal-mistakes/docs/helpers/#table-of-contents

**Comment by Signior-X** [comment]
Should I try this one?

**Comment by PIYUSHgoyal16** [comment]
> @PIYUSHgoyal16 I think you want something like this: http://blog.pc.iitmandi.co.in/web-development-for-freshers/. If so, you only need to set `toc : true` and probably the `toc_label`. For reference: https://raw.githubusercontent.com/KamandPrompt/blog/master/_posts/2020-05-25-web-development-for-freshers.md

Not exactly, I want the sidebar to remain intact even when the user scrolls down. Something like the left-hand side, the author profile in case of your example :-)

**Comment by PIYUSHgoyal16** [comment]
> Should I try this one?

Sure @Signior-X Do let us know if you are stuck somewhere :-)
