### ISSUE TITLE
Migrate GSoC 2019 project ideas page from old website

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#12]
Migrate https://wiki.linuxfoundation.org/gsoc/google-summer-code-2019-openprinting-projects

The different ideas should have different pages so that they are manageable and easily editable.

Depends on: #14

**Comment by rithvikp1998** [comment]
Resolved within #20 itself

**Comment by sahilarora535** [comment]
Thank you very much @rithvikp1998
