### ISSUE TITLE
Add openprinting logo beside the title on the title bar

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#13]
The title bar looks like this:

![image](https://user-images.githubusercontent.com/12633577/51423701-c81a2f80-1be9-11e9-9ad8-d470f217dc2f.png)

It would be great to have the openprinting logo beside the title "OpenPrinting" on the title bar.

**Comment by dheeraj135** [comment]
Hi @sahilarora535 , I looked into this issue and this is the result:
![screenshot from 2019-01-20 23-38-33](https://user-images.githubusercontent.com/28601604/51443295-ab2a4d00-1d0c-11e9-916b-d40367dc791b.png)

**Comment by sahilarora535** [comment]
Closed in #21
