### ISSUE TITLE
"Help" link is dead – No idea where to get help

### ISSUE THREAD

**Issue by genodeftest** [OpenPrinting/openprinting.github.io#132]
Background: I get weird artifacts so I wanted to have a look where I can get help for that problem.

A search engine sent me to https://openprinting.github.io/cups/doc/reporting-bugs.html which contains a prominent link [Help / Documentation](https://openprinting.github.io/index.html#DOCUMENTATION).

What happens:
After clicking that link, I can see documentation but no way to get help.

What do I expect to happen:
Any kind of instructions where/how to get help.

**Comment by michaelrsweet** [comment]
This looks like a Github Pages bug - the link isn't getting expanded properly under openprinting. Changing it to an absolute link to the CUPS home page's documentation section.
