### ISSUE TITLE
Images on downloads page need fixing in dark mode

### ISSUE THREAD

**Issue by diddledani** [OpenPrinting/openprinting.github.io#134]
When your browser is set to dark mode, and thus triggering the page to be black due to the `@media (prefers-dark-mode: true) {}` CSS rules, the images on https://openprinting.github.io/downloads/ are not visible. This is because they are black lines with transparency and so they blend with the dark mode black page background.

A fix could be to use something like CSS rule of `filter: invert();` but I can't see how to explicitly select those images and not images on other pages. An alternative fix would be to ensure the images have an opaque background instead of transparent, similar to the white background applied to the images on the "about us", "contribute", and "cups" boxes at https://openprinting.github.io/.

![image](https://user-images.githubusercontent.com/147548/136438922-09e314b0-9f71-4f46-a59a-df1d37c79cc0.png)

**Comment by michaelrsweet** [comment]
I fixed this on the home page already, and it looks like that fix also fixed the downloads page...
