### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by NeilRickards** [OpenPrinting/openprinting.github.io#136]
The [login link](https://openprinting.org/login) at https://openprinting.org/printers redirects to https://identity.linuxfoundation.org/cas/login which is giving an "unknown service" response

**Comment by michaelrsweet** [comment]
@tillkamppeter This is an issue with the older web site you maintain...

**Comment by NeilRickards** [comment]
Thanks @tillkamppeter.  You list my printer as a "paperweight" but I was able to get it working using CUPS.  I was going to contribute this information back.  If user contributions are no longer supported then happy to close this ticket.
Thanks both for maintaining CUPS - this and a Raspberry Pi have saved at least one printer from landfill!

**Comment by tillkamppeter** [comment]
@NeilRickards please report an issue on [foomatic-db](https://github.com/OpenPrinting/foomatic-db/issues), tell us exactly which printer model you have and how you made it working with CUPS in your issue report.
