### ISSUE TITLE
Have a more helpful introduction for the website

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#15]
The introduction for the website, as mentioned below, might require a change so that people who visit the website for the first time know what the site is all about:

![image](https://user-images.githubusercontent.com/12633577/51423886-627b7280-1bec-11e9-8cf3-73304d89dc2c.png)

@tillkamppeter @iramcdonald @AveekBasu  It would be great if you could suggest some meaningful introduction, or does the current introduction work?

**Comment by dheeraj135** [comment]
@sahilarora535 I think this will be better: 
**_Making printing just work_** on free operating systems like GNU/Linux and the BSDs or under commercial UNIX-like systems such as Solaris and Mac OS X.

**Comment by iramcdonald** [comment]
Hi,

I disagree with this suggestion.

Grey area here - OpenPrinting WG collaborates closely w/ IEEE-ISTO
Printer Working Group on IPP projects (underlying both CUPS Filters
and Apple CUPS).

IPP has shipped for years on Apple macOS and iOS.  IPP (via Android
Mopria compliance) started shipping on Windows 10 in the current
release.

OpenPrinting WG is part of that larger standards-based printing
ecosystem and not exclusively focused on free software printing.

Also note that IEEE-ISTO PWG maintains an open source IPP
sample code repository which includes both 'ipptool' (the test
tool for developers and self-certification) and 'ippserver" (which
has a reference implementation of most of the IETF and PWG
standard IPP operations and attributes and is extended for
prototyping w/ all new PWG IPP standards specs.

The 'ipptool' PWG self-certification service for IPP Everywhere
compliance has Linux, macOS, and Windows binaries.

Cheers,
- Ira (wearing both PWG IPP co-chair and LF OP chair hats).


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by dheeraj135** [comment]
@iramcdonald @tillkamppeter @sahilarora535 Please have a look into this introduction: [Google docs](https://docs.google.com/document/d/1rnaqkFX7Dsjp7xecyWV3Fum15EKZRC3PJ2kH4Nz7UrA/edit?usp=sharing). Please feel free to edit it and post comments. 

We can also use this introduction in **about** section. @rithvikp1998

**Comment by tillkamppeter** [comment]
I have edited the text somewhat, mainly for upper/lowercase and the correct project names. "PWG" should be a link to www.pwg.org.
We should change the text somehow that "OpenPrinting" does not appear that often. Perhaps we should put OpenPrinting's projects/work areas into a bulleted list.

**Comment by iramcdonald** [comment]
Hi,

I agree with Till - a bullet list of OP projects might be crisper and more
readable.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by dheeraj135** [comment]
@rithvikp1998 Looks good to me. You can use this text in the about page. 
For the introduction we need only one or two lines. I will work on the introduction.

**Comment by tillkamppeter** [comment]
Note that we did not yet have any collaboration with SANE. This summer will be the first time where we work on IPP scanning, and there we do not yet know whether we really get SANE developers working with us (for example as mentor) or whether we simply only contribute the SANE driver for driverless IPP network scanners to the SANE project.

**Comment by dheeraj135** [comment]
Thanks @tillkamppeter for the input. I will change it.
