### ISSUE TITLE
Add an About page for the website

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#16]
Every website has an **About Us** or similar page which tells what's the website is all about, and important links to various other pages in the website, very similar to this: https://wiki.linuxfoundation.org/openprinting/start

A start page for the new website would be amazing.
@tillkamppeter @AveekBasu should the content from the old start page be directly copied or would you prefer some new content?

**Comment by rithvikp1998** [comment]
I put up a blank page in https://github.com/OpenPrinting/openprinting.github.io/pull/27/commits/cc9a79eb10af2c078b27af50d281a8c2a1705fe5 but I have no ideas about the content that should be in it.

**Comment by rithvikp1998** [comment]
Fixed with e6c6051832cab29a5785eadb5160f43ecc2f76f3
