### ISSUE TITLE
Add a page for contributing to the development of the website

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#17]
We need a page on the website for contributing to the development of the website, and a contributing guide **Contributing.md** in the source code so that anyone new to the website can contribute without a lot of manual help or instructions.

**Comment by dheeraj135** [comment]
@sahilarora535 Please have a look on this page: https://dheeraj135.github.io/openprinting.github.io/contribute-website/ .

**Comment by sahilarora535** [comment]
Closed in #21
