### ISSUE TITLE
CSS transition not working in chrome based browsers.

### ISSUE THREAD

**Issue by dheeraj135** [OpenPrinting/openprinting.github.io#22]
CSS transition responsible for showing blue line when we hover over elements of Menu bar doesn't work properly in chromium based browsers(Google chrome and chromium-browser).

**Comment by tillkamppeter** [comment]
On my Chromium browser (Ubuntu 18.10, "Version 71.0.3578.98 (Official Build) Built on Ubuntu , running on Ubuntu 18.10 (64-bit)") the blue lines appear under the main menu entries when hovering over them.

**Comment by dheeraj135** [comment]
@tillkamppeter Blue line appears, but animation is not working.
This is the animation for blue line: 
```  transition: all 0.2s ease-in-out;  ```
Can you please verify whether animation is working on your browser?

**Comment by tillkamppeter** [comment]
I have opened the page on Firefox now and now I see what you mean. This animation is actually missing on Chromium.

**Comment by dheeraj135** [comment]
This bug is not reproducible on latest chrome browsers. Closing this issue.
