### ISSUE TITLE
Add comment dialogue to pages

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#25]
Right now, we do not have a capability that a user can comment on a page we wrote. We need to enable commenting capability in the website using disqus or some other framework. WDYT @tillkamppeter , would this make sense?

**Comment by dheeraj135** [comment]
@sahilarora535 I think we need this comment feature only on posts(News and Events).

**Comment by dheeraj135** [comment]
I will be working on this issue.

**Comment by dheeraj135** [comment]
@tillkamppeter Can you please share Disqus short-name of your account?

**Comment by tillkamppeter** [comment]
The Disqus user name is tillkamppeter

https://disqus.com/by/tillkamppeter/

**Comment by dheeraj135** [comment]
@tillkamppeter This is not short-name. Disqus now needs short-name for the website. You will have to add a new site in the [admin panel of Disqus](https://disqus.com/admin/).

**Comment by tillkamppeter** [comment]
I have found it now, the web site short name is `openprintingorg`.

**Comment by dheeraj135** [comment]
We cannot use ``` openprintingorg ``` because it shows ads. I created another web site with a plan without ads(pro account) for testing purposes. [Link](https://dheeraj135.github.io/dheeraj135.github.io_change/website-is-up/).

I think Disqus allows you to change subscription of your web site. So, either we need to change subscription or create a new web site with required subscription.

**Comment by tillkamppeter** [comment]
We should perhaps find some free software comment system to run on the old OpenPrinting server) there I am root and it stays running for the Foomatic database). This way the Linux Foundation is hosting and we have no costs, neither money to pay nor ads to accept. We also keep the control on the content of the user comments.
We should always avoid external commercial services.

**Comment by sahilarora535** [comment]
@dheeraj135 Have a look at what all commenting frameworks are already added to the theme: https://mmistakes.github.io/minimal-mistakes/docs/configuration/#comments

**Comment by dheeraj135** [comment]
We have following alternatives:
1. Disqus  
We can use their free service which doesn't serve ads. We will not have to worry about hosting and other stuff. The only issue is that we can have only up to 50000 daily page views.  Disqus also have one of the best UI.
2. Discourse
Discourse requires proper hostname for the server(IP will not work) and HTTPS needs to be set up. 
3. Talkyard
Talkyard is easy to setup.
4. Staticman or Utterances
Staticman creates new PR for each comment and Utterances create a new issue for each thread. So, I don't think we should use any of these.
5. Facebook or Google+
They need the user to be logged into their respective platform.

If we have less than 50,000 daily page views Disqus is the best option otherwise we can go for Discourse or Talkyard.

@sahilarora535

**Comment by tillkamppeter** [comment]
Note also that Google+ is discontinued and will shut down on April 1st (other Google services like GMail, Google Drive, ... continue).
Note also that not everyone (including me) wants to have a Facebook account.
The 50000 pafe views limit of Disqus is a risk.
I think Discourse is a good choice.

**Comment by dheeraj135** [comment]
@tillkamppeter So, let's go with Discourse. You will have to set up the Discourse server.

**Comment by iramcdonald** [comment]
Hi,

WAIT!  The chance of 50,000 *daily* page views is ZERO.
I favor the simpler to set up and maintain Disqus option.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by sahilarora535** [comment]
I agree with @iramcdonald. Disqus is safe bet here. A lot of the open source sites use it, and it will be a lot of pain to maintain a discourse server if we don't intend to use it, which we don't at the moment. We must avoid any complex and unnecessary setup. I think Disqus is the best bet here.

**Comment by dheeraj135** [comment]
@tillkamppeter @iramcdonald @sahilarora535 I suggest we should right now go with Disqus and switch to Discourse if website traffic starts increasing. 

We can consider setting up Discourse forums as a future goal. After forums are set up, it can be used to replace mailing lists and provide the OpenPrinting community with a better platform to discuss.

**Comment by dheeraj135** [comment]
@tillkamppeter @iramcdonald @sahilarora535 What is the final decision on this issue?

**Comment by sahilarora535** [comment]
I'd prefer Disqus and get the site running, and if we face a problem in the future, then find an alternative solution. I hope that makes sense.

**Comment by iramcdonald** [comment]
Hi,

I agree with Sahil.  Consensus is Disqus.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by tillkamppeter** [comment]
OK, let us go with Disqus.
