### ISSUE TITLE
Add projects and content to the projects page

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#31]
The `projects` page should have some content and useful information about the different projects it has. Ideally, the `projects` should be a collection with a list of pages which describe each project. Then, in each project's page, we should have a link to the documentation of that particular project. This will should be the complete flow of the projects site.
Depends on: #30

**Comment by dheeraj135** [comment]
@sahilarora535 Does this [page](https://wiki.linuxfoundation.org/openprinting/database/projects) contains all the projects of OP?

**Comment by tillkamppeter** [comment]
This page is totally outdated.
Current free software projects are:
- cups-filters
- ippusbxd
- Foomatic
- Common Print Dialog Backends
As printing systems/spoolers we currently only support CUPS as this is what is actually used and everything else (like LPD, LPRng, ...) is not maintained upstream any more.
what we also do in general:
- Implementing PWG standards for Linux and other Posix-style operating systems
- Support for driverless printing
- Work with printer manufacturers on making printer drivers
