### ISSUE TITLE
Add content to the 'Contact Us' Page

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#33]
Add content to the `Contact Us` page which would be located here: https://openprinting.github.io/contact/

Depends on: #32

**Comment by Sharadd15** [comment]
@sahilarora535  can we implement mailer for this using php? the user will enter the name and a valid email address and a message box to write the message. The user will receive a thank you mail from us and we can forward the message to our mail-list ? or you have something else in mind ? i would like to work on this

**Comment by dheeraj135** [comment]
@Sharadd15 This website is a static website, hosted on Github pages and powered by Jekyll. So, we cannot use any server-side languages. For the Contact Us page, we simply need to describe the ways in which a person can contact OP WG like mailing lists. Do have a look here: [Mailing Lists](https://wiki.linuxfoundation.org/openprinting/development#mailing_lists). 
This issue depends on #32 . That issue is already solved, but PR is yet to be merged. Till then, you can prepare content.
Also, please use Jekyll layouts and markdown when writing the page.

**Comment by Sharadd15** [comment]
Yeah I noticed that a bit later but still we can make a form by using some external source like [forms free](https://formspree.io/) which provides with free 1000 submissions per month . if we will be having less than 1000 submission per month then this will be more user interactive or we can just create the page with the three mailing list as described on this page [Mailing Lists](https://wiki.linuxfoundation.org/openprinting/development#mailing_lists) or are we planning to do something else @sahilarora535 ?

**Comment by dheeraj135** [comment]
@Sharadd15 It is better not to make any assumptions as discussed here: #25 . Also, we are planning to deploy discourse server, after server is deployed users can directly discuss on discourse forums.

**Comment by tillkamppeter** [comment]
I am against formspree, as as most commercial services they are limited for non-paying users. It should not be too complex to code a simple web form which takes the content of the input field and send it to an e-mail address (probably there is already some free software doing this).

**Comment by sahilarora535** [comment]
@Sharadd15 @dheeraj135 Thank you for your valuable inputs. The purpose of contact us page is that anyone should be able to contact us. So even if we have a simple email to send an email to, that would do the same task as a form where user will write his content. Usually, people create such contact us forms when either they don't want to be contacted, or they don't want to share their email. We don't want that here. Hence we can go with the much simpler solution of having an email ID. Does that make sense to you?

**Comment by iramcdonald** [comment]
Hi,

Yes I agree that a simple email address is best for the contact info.
We don't want to hide or discourage contact.  We want people to
find us easily.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434
