### ISSUE TITLE
Create a 'Donations' page

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#34]
Create a `Donations` page in the `_pages` directory which would contain the different ways someone can donate to openprinting. The page should be located here: https://openprinting.github.io/donations/
Initially, the page should be empty, we will create a new issue to add data to it.

**Comment by iramcdonald** [comment]
Hi,

This may have changed, but...

OP is not an incorporated entity in its own right.

In the past it was impossible to make a financial donation to OP.  One could
only make a donation to Linux Foundation that was earmarked for use by OP
(and that notation was non-binding on LF).

Till may know the current status.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by sahilarora535** [comment]
@tillkamppeter Could you kindly shed some light on this?

**Comment by tillkamppeter** [comment]
@iramcdonald, I think there nothing has changed. We can perhaps simply tell that it is this way on our donations page.
We also should say that we are accepting hardware samples for testing and development.

**Comment by sahilarora535** [comment]
Closed in f0e95dc0619324b6bf35a3cc6f6a41c945d05fe9
