### ISSUE TITLE
Add content to the 'Downloads' page

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#37]
Add content to the `Downloads` page located here: https://openprinting.github.io/downloads/
Depends on: #36

**Comment by Sharadd15** [comment]
I would like to work on this issue. @sahilarora535, @AveekBasu  can you please tell me what is the content should be added on this page ?

**Comment by dheeraj135** [comment]
@Sharadd15 Please do have a look here: [Downloads](http://www.openprinting.org/download/). Most of the content is already there on the old website, we just have to migrate it. Please use Jekyll layouts and markdown for writing the page.

@sahilarora535 @tillkamppeter For the downloads, should we add that content to this repo itself or let them stay on the old website.

**Comment by tillkamppeter** [comment]
Please leave the downloadable files itself on the old server and do not make them part of a GIT repository. GIT is not made for managing binary files and these downloadable files would make the site's repo huge, making its download near impossible.
