### ISSUE TITLE
The GSoC 2019 projects page should have sidebars

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/openprinting.github.io#39]
Create two navigation sidebars, one with links to different projects on the left, and one on the right with the contents of the page, for the GSoC 2019 page. Have a look here for a sample: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

This is a feature supported natively in the theme.

![image](https://user-images.githubusercontent.com/12633577/52178788-86e46b00-27f8-11e9-9604-7de0f73244b9.png)

**Comment by dheeraj135** [comment]
I am working on this issue.
