### ISSUE TITLE
Change CSS of links.

### ISSUE THREAD

**Issue by dheeraj135** [OpenPrinting/openprinting.github.io#48]
Currently, links in the body look like this:
![screenshot from 2019-02-26 15-37-20](https://user-images.githubusercontent.com/28601604/53404851-847ec680-39dc-11e9-86af-37d2b8791cef.png)

They should look something like this:
![screenshot from 2019-02-26 15-37-05](https://user-images.githubusercontent.com/28601604/53404856-89437a80-39dc-11e9-98d1-4ec1c836f435.png)

Suggestions are welcome.

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by dheeraj135** [comment]
Hey @gaurivn, Thank you for you interest. As you can see, the links in the first pic looks dull. I had previously done these changes on the [News page](https://openprinting.github.io/news/). These changes needs to be propagated to other pages i.e. [Projects](https://openprinting.github.io/projects/), [Upcoming Technologies](https://openprinting.github.io/upcoming-technologies/) and [Gsoc](https://openprinting.github.io/gsoc/). Please focus on making the changes on the website scope and, don't do it for each and every single page. This way it would be much more maintainable.

**Comment by gaurivn** [comment]
> Hey @gaurivn, Thank you for you interest. As you can see, the links in the first pic looks dull. I had previously done these changes on the [News page](https://openprinting.github.io/news/). These changes needs to be propagated to other pages i.e. [Projects](https://openprinting.github.io/projects/), [Upcoming Technologies](https://openprinting.github.io/upcoming-technologies/) and [Gsoc](https://openprinting.github.io/gsoc/). Please focus on making these changes on the website scope. This way it would be much more maintainable.

Sure @dheeraj135, thank you for explaining.

**Comment by gaurivn** [comment]
> Hey @gaurivn, Thank you for you interest. As you can see, the links in the first pic looks dull. I had previously done these changes on the [News page](https://openprinting.github.io/news/). These changes needs to be propagated to other pages i.e. [Projects](https://openprinting.github.io/projects/), [Upcoming Technologies](https://openprinting.github.io/upcoming-technologies/) and [Gsoc](https://openprinting.github.io/gsoc/). Please focus on making these changes on the website scope. This way it would be much more maintainable.

@dheeraj135, I have set up the environment, went through news, and the other parts whose links need to be changed but couldn't figure out where exactly to make changes...grateful if you could give more hints.

**Comment by dheeraj135** [comment]
This website is based on jekyll. In jekyll, we use layouts for pages. The news section uses posts.html layout. Look at the div tag with [class post](https://github.com/OpenPrinting/openprinting.github.io/blob/230f4900f14ae14486f857c921f2cb2dde385005/_layouts/posts.html#L24). We have custom css for post class. Note that the projects, upcoming technologies and gsoc page are using the collections layout. So, you can make changes to the collection layout. 
If you are not familiar with Jekyll, Please take a look at the [CONTRIBUTING.md](https://github.com/OpenPrinting/openprinting.github.io/blob/master/CONTRIBUTING.md) file.

**Comment by Signior-X** [comment]
@dheeraj135 should I try?

**Comment by dheeraj135** [comment]
> @dheeraj135 should I try?

Sure, please go ahead.
