### ISSUE TITLE
Create a collection for news items

### ISSUE THREAD

**Issue by AveekBasu** [OpenPrinting/openprinting.github.io#5]
Will show up the latest blog posts over here.

(Reference section in Libreoffice.org: posts feeds)

**Comment by dheeraj135** [comment]
@sahilarora535 Do we really need separate news and blog sections? If so, please elaborate role of both sections.

**Comment by iramcdonald** [comment]
Hi,

I also think we should concatenate News and Blogs into one section/menu
item.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by tillkamppeter** [comment]
My original intention was using the blog functionality of Jekyll for easily posting news items. A separate blog is not needed.

**Comment by dheeraj135** [comment]
I am working on this issue.
