### ISSUE TITLE
Migrate foomatic database.

### ISSUE THREAD

**Issue by dheeraj135** [OpenPrinting/openprinting.github.io#54]
Reference: [Github Project Link](https://github.com/OpenPrinting/openprinting.github.io/projects/1#card-14830318)
It is not possible to host server-side applications on GitHub, so PHP is out. I think the required task can be accomplished with Jekyll, but it will require all the files to be present in the GitHub repo. @tillkamppeter @sahilarora535

**Comment by sahilarora535** [comment]
@dheeraj135 I do not have much context on this one. Could you please explain in detail what the problem exactly is and why we need a database, what is exactly stored in the database and who needs access to the DB?

**Comment by tillkamppeter** [comment]
For the Foomatic migration we do not intend to pull the whole thing away from the LF's servers, but what we need to do is the following:
1. Move the BZR repositories related to Foomatic and the web app to GitHub, converted to GIT (preserving commit history).
2. Modify the code of the (PHP) web app (which will stay running on the server where it is currently running) and its accompanying scripts to use the new GIT repositories of Foomatic instead of the old BZR ones.
3. Change the corporate identity (logo, ...) of the PHP-web-app-generated pages to match our new static web site.

So GitHub will only host the repositories, the web app and the MySQL database will stay where they are currently.

**Comment by dheeraj135** [comment]
@tillkamppeter Can you please provide links to the relevant bazaar repositories?

**Comment by tillkamppeter** [comment]
These are the BZR repositories of what is still in use:
- foomatic-db: http://bzr.linuxfoundation.org/loggerhead/openprinting/foomatic/foomatic-db/files
- foomatic-db-engine: http://bzr.linuxfoundation.org/loggerhead/openprinting/foomatic-4.0/foomatic-db-engine/files
- web app: http://bzr.linuxfoundation.org/loggerhead/openprinting/misc/printing-new-devel/files

**Comment by tillkamppeter** [comment]
By the way, this is the full set of old BZR repositories of OpenPrinting, but most are not maintained any more:
http://bzr.linuxfoundation.org/loggerhead/openprinting/

**Comment by dheeraj135** [comment]
I have pushed the repositories on GitHub:
foomatic-db : https://github.com/dheeraj135/foomatic-db
foomattc-db-engine: https://github.com/dheeraj135/foomatic-db-engine
Web App: https://github.com/dheeraj135/OpenPrinting-Web-App
@tillkamppeter Please move these repositories to OpenPrinting Organization, so that we can use OpenPrinting repositories in PHP code and other scripts.

**Comment by dheeraj135** [comment]
@tillkamppeter I am having some trouble in setting up phpCAS. What is the best way to test all the scripts for git? Is phpCAS necessary for testing purposes? If phpCAS is necessary, which version do you use on your server and how to configure it on apache?

**Comment by tillkamppeter** [comment]
[phpCAS](https://apereo.github.io/cas/6.0.x/index.html) seems to be the single-sign-on system of the Linux Foundation. It is used in the following files:
- `inc/session.php`
- `inc/user.php`

Probably it is for supporting features where users can contribute data. For interaction with GIT or BZR repositories it should not be relevant.

**Comment by dheeraj135** [comment]
@tillkamppeter ```To transfer repositories to an organization, you must have repository creation permissions in the receiving organization.```. I don't have sufficient permissions to create a repository on OpenPrinting organization. 
Error:
```You don’t have the permission to create repositories on OpenPrinting ```

**Comment by tillkamppeter** [comment]
I have now simply imported all the relevant projects by myself, to make it simpler.
I havre done the following changes/corrections:
- Added foomatic-db-nonfree, I had forgotten it in the first place
- I have added 2 repositories for foomatic-db-engine. foomatic-db-engine is the development branch used by the web app, foomatic-db-engine-4 (it has releases) is the stable branch used by the distros. We should discontinue this stable branch and do releases in the development branch to have only one, especially if there is practically no further development any more.
- I have renamed printing-new-devel to foomatic-db-webapp

Note that I have not entered project descriptions yet. I will do this later.

**Comment by tillkamppeter** [comment]
Descriptions added.

**Comment by dheeraj135** [comment]
@tillkamppeter Can you please share versions of mysql, php, apache and linux distro you are using on the server?

**Comment by tillkamppeter** [comment]
Distro: Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-126-generic x86_64)
Packages for MySQL, PHP, Apache installed on the server, with their versions:
```
till@openprinting2:~$ dpkg -l | grep mysql
ii  libdbd-mysql-perl                          4.020-1ubuntu0.1                  Perl5 database interface to the MySQL database
ii  libmysqlclient18                           5.5.54-0ubuntu0.12.04.1           MySQL database client library
ii  mysql-client-5.5                           5.5.54-0ubuntu0.12.04.1           MySQL database client binaries
ii  mysql-client-core-5.5                      5.5.54-0ubuntu0.12.04.1           MySQL database core client binaries
ii  mysql-common                               5.5.54-0ubuntu0.12.04.1           MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                               5.5.54-0ubuntu0.12.04.1           MySQL database server (metapackage depending on the latest version)
ii  mysql-server-5.5                           5.5.54-0ubuntu0.12.04.1           MySQL database server binaries and system database setup
ii  mysql-server-core-5.5                      5.5.54-0ubuntu0.12.04.1           MySQL database server binaries
ii  php5-mysql                                 5.3.10-1ubuntu3.26                MySQL module for php5
till@openprinting2:~$ dpkg -l | grep apache
ii  apache2                                    2.2.22-1ubuntu1.11                Apache HTTP Server metapackage
ii  apache2-mpm-prefork                        2.2.22-1ubuntu1.11                Apache HTTP Server - traditional non-threaded model
ii  apache2-utils                              2.2.22-1ubuntu1.11                utility programs for webservers
ii  apache2.2-bin                              2.2.22-1ubuntu1.11                Apache HTTP Server common binary files
ii  apache2.2-common                           2.2.22-1ubuntu1.11                Apache HTTP Server common files
ii  libapache2-mod-php5                        5.3.10-1ubuntu3.26                server-side, HTML-embedded scripting language (Apache 2 module)
till@openprinting2:~$ dpkg -l | grep php
ii  libapache2-mod-php5                        5.3.10-1ubuntu3.26                server-side, HTML-embedded scripting language (Apache 2 module)
ii  libphp-phpmailer                           5.1-1+deb6u11build0.12.04.1       full featured email transfer class for PHP
ii  php-apc                                    3.1.7-1                           APC (Alternative PHP Cache) module for PHP 5
ii  php-pear                                   5.3.10-1ubuntu3.26                PEAR - PHP Extension and Application Repository
ii  php5-cli                                   5.3.10-1ubuntu3.26                command-line interpreter for the php5 scripting language
ii  php5-common                                5.3.10-1ubuntu3.26                Common files for packages built from the php5 source
ii  php5-curl                                  5.3.10-1ubuntu3.26                CURL module for php5
ii  php5-dev                                   5.3.10-1ubuntu3.26                Files for PHP5 module development
ii  php5-ldap                                  5.3.10-1ubuntu3.26                LDAP module for php5
ii  php5-mysql                                 5.3.10-1ubuntu3.26                MySQL module for php5
till@openprinting2:~$ 
```
Note that the actual MySQL database is on an external server, but it should use similar versions.

**Comment by tillkamppeter** [comment]
[Here](http://www.openprinting.org/download/tmp/apache-config.tar.gz) is the content of the server's /etc/apache2/ directory.

**Comment by tillkamppeter** [comment]
What you need to do at first is to create a script
```
maint/scripts/updatemysqlfromgit
```
which does the same as
```
maint/scripts/updatemysqlfrombzr
```
but taking the changes from the GIT repository and not from the old BZR repository.
To make testing easier you should perhaps modify the files `inc/session.php` and `inc/user.php` so that they do not break anything if phpCAS is missing. The should handle the absense gracefully (to at least have read-only access to the site) but work normally, using phpCAS if it is present.
Otherwise the web app needs to be fit to the look and feel of the new static web site (new logo and so on).

**Comment by dheeraj135** [comment]
@tillkamppeter I have ported all the relevant scripts to use git. I need to test them. I have tested ```importfromgit```.  What is the best way to test all the scripts?

**Comment by tillkamppeter** [comment]
Could you make your new code/scripts available to me? I could test them on the real server.
Did you try to set up a server by yourself?

**Comment by dheeraj135** [comment]
I do have a server set up(except for authentication). Scripts are available here: https://github.com/dheeraj135/foomatic-db-webapp/commit/7700e4bb3e30bc71745cec09ad43d82290df58e8  and [Github Repo](https://github.com/dheeraj135/foomatic-db-webapp). Please test the scripts on the real server because only you know about all the possible scenarios.

**Comment by tillkamppeter** [comment]
@dheeraj135, thank you very much for your scripts. Did you test all of them? If yes, how? Did you succeed to make a working copy of the server/the web app? You could fork foomatic-db and foomatic-db-nonfree into your GitHub and then let your server point to your GitHub, then do changes in foomatic-db and/or foomatic--db-nonfree on your GitHub (including adding/removing/modifying XML files and manufacturer PPDs, after pushing your changes, run `cd /srv/www/openprinting/; ./maint/scripts/updatemysqlfromgit`. Thids should apply the changes to the web app.

**Comment by dheeraj135** [comment]
No, I didn't test all of them. I have a working copy of the web app in a virtual machine running Ubuntu 12.04. I will test the scripts.

**Comment by dheeraj135** [comment]
@tillkamppeter I have found some serious bugs in the scripts. I will make the required changes and then notify you.

**Comment by tillkamppeter** [comment]
@dheeraj135, did you work on the "serious bugs" which you have found?

**Comment by dheeraj135** [comment]
@tillkamppeter I am working on it.

**Comment by dheeraj135** [comment]
Hi @tillkamppeter, 
We have many printers and drivers which are not included in the foomatic package [Example](http://openprinting.org/printer/Brother/Brother-MFC-J480DW), but these are necessary for the web app.

Possible Solution:
We can create another package especially for the web app(something like ```foomatic-db-untrusted``` ) and use that for setup purposes.
 
Next issue is, some printers are included in the ```foomatic-db``` package but there is an entry in git log to delete these printers in ```foomatic-db-nonfree``` package. So, if we import from ```foomatic-db-nonfree``` after importing ```foomatic-db```, these printers get deleted. Probably, they were moved from ```nonfree``` to ```foomatic-db```. Commit: https://github.com/OpenPrinting/foomatic-db-nonfree/commit/f29fa029b7e497488b1d4d5149b9336dd3e93ac2

Possible Solution:
I have written a new script for adding data into the MySQL server during the initial setup(```loaddb```), in that script we can disable deleting of printers from the server during the setup. 

What do you think will be the best solution here?

**Comment by tillkamppeter** [comment]
The printer entry which you have given as example is a user contribution without our approval. It should not be in the foomatic-db package. It is only a printer entry with no driver entry related to it. These are only in the server's MySQL database not in Foomatic XML. These entries will stay conserved if on the server the old BZR-based we app is replaced by the new GIT-based one, so no extraction of these entries to XML is needed.
No problem that there is a commit in `foomatic-db-nonfree` which deleted all printer entries. `foomatic-db-nonfree` was started as a copy of `foomatic-db`. Near the beginning of its history all which was present in both (and so duplicate in total) was removed from `foomatic-db-nonfree`. Note that you will not replay the commits of `foomatic-db-nonfree` on `foomatic-db` but take all files of `foomatic-db` and all files of `foomatic-db-nonfree` to make up the whole thing. There should be no duplicates.

**Comment by dheeraj135** [comment]
@tillkamppeter, I have updated the scripts [Github](https://github.com/dheeraj135/foomatic-db-webapp). Please test all scripts on the server. 
For testing ```updatemysqlfromgit```, I added and removed some files from the repository. 
```makesnapshotgit``` is also working fine.
I was not able to test ```commitppdtogit```, because I was not able to add ppds on the server. How to test this script?
If you are setting up a new server, then please use ```loaddb``` script to load data into the database.

**Comment by tillkamppeter** [comment]
What is `loaddb` good for? Is it for initial population of the empty database with the Foomatic GIT repos? Or is it to update the populated MySQL database with the last changes (this I would expect is the task of `updatemysqlfromgit`, what would be the difference then?)?

**Comment by dheeraj135** [comment]
@tillkamppeter ```loaddb``` is only for the initial population of the empty database. 
```loaddb``` is important because when we use ```git diff``` to get files changed between initial and current commit, files which are not changed after the initial commit are not loaded into the database. ```loaddb``` also addresses the "printers getting deleted" issue which I mentioned earlier.

**Comment by tillkamppeter** [comment]
Are sure that your `loaddb` script is not adding printers to the database which were created somewhere in the history of Foomatic and later deleted again? Is it not much simpler and safer for an initial population of the MySQL database to clone foomatic-db and foomatic-db-nonfree, copy its `db/` subdirectories into the same temporary directory and then import all these files into the MySQL database? Note that the MySQL database only carries the current state of Foomatic, not its history.

**Comment by tillkamppeter** [comment]
Another thing:
On the production server the MySQL database is already populated.
So can I replace the server's foomatic/foomatic-db and foomatic/foomatic-db-nonfree directories by `git clone`s of the appropriate repos and from then on run `updatemysqlfromgit` (I have already manually copied your new files onto the production server) on the server to update the MySQL database with the changes in the GIT of foomatic-db and foomatic-db-nonfree?

**Comment by dheeraj135** [comment]
I was thinking about the same thing. I will change the```loaddb``` script. 

Regarding ```updatemysqlfromgit```:
It should work. But I suggest not to try directly on the production server.

**Comment by tillkamppeter** [comment]
I have switched over the server. Thank you very much for your work.
Please make a pull request of your repo, so that I can take your scripts into the official repo.

**Comment by tillkamppeter** [comment]
@dheeraj135, thank you for the [pull request #1 on foomatic-db-webapp](https://github.com/OpenPrinting/foomatic-db-webapp/pull/1). I have merged it now and so from now on we will use GIT also for Foomatic.
Next step for the web app is to match its appearance with the new web site.
