### ISSUE TITLE
OpenPrinting database web app needs to get converted to the new corporate identity

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/openprinting.github.io#58]
The web app for accessing the OpenPrinting printer/driver database:
http://www.openprinting.org/printers/
http://www.openprinting.org/drivers/
needs to get the outfit of our new web site: log, colors, ...

**Comment by sahilarora535** [comment]
@tillkamppeter If this database at the backend of these two pages is not sensitive, could we get a dump of the data the database has, so that we can come up with a design on how to add this to the new website?

**Comment by dheeraj135** [comment]
Hi Sahil,

The webserver's code is located at
https://github.com/openprinting/foomatic-db-webapp
It automatically pulls any changes in the foomatic-db github repository and
updates the server. This way we only have to update the foomatic repository.
The current webserver is running on Ubuntu 12.04.

**Comment by dheeraj135** [comment]
@tillkamppeter In the footnotes of webpage https://openprinting.org/printers, we have ```Copyright 2013 Linux Foundation. All rights reserved.```. Should we remove it?

**Comment by tillkamppeter** [comment]
Done, thanlk you very much, @dheeraj135!
