### ISSUE TITLE
Driverless Printing is hidden from OP home page

### ISSUE THREAD

**Issue by iramcdonald** [OpenPrinting/openprinting.github.io#63]
From the home page, there should be a tab to Driverless Printing.

I could only navigate there via Projects->Miscellaneous
- oops.

Also, IPP Everywhere logo should be on the main Driverless
Printing page (not just in the Standards sub-page).

**Comment by sahilarora535** [comment]
@iramcdonald The driverless printing page link is right on the menu bar of the website, it's collapsed:
![image](https://user-images.githubusercontent.com/12633577/66528110-6190c500-eb1c-11e9-847c-cdaf2bc6f211.png)

You can find it here: https://openprinting.github.io/driverless/

Also, you are right, we should add the IPP everywhere logo on all the driverless pages.

**Comment by iramcdonald** [comment]
Hi Sahil,

Sorry - I didn't know it was a menu bar and had never opened it.

I'd still like to see Driverless Printing as a main topic under
Projects (and not hidden under Miscellaneous, which sounds
like "not very important" to me).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434
