### ISSUE TITLE
Add link for OP monthly call minutes to OP Website

### ISSUE THREAD

**Issue by iramcdonald** [OpenPrinting/openprinting.github.io#71]
Till and Aveek can probably suggest just where to put this link.
For many years the OP monthly call minutes have been durably archived (in HTML) at:

http://ftp.pwg.org/pub/pwg/liaison/openprinting/minutes/

**Comment by dheeraj135** [comment]
@iramcdonald We can add this link somewhere on the news and events section.
@JaiLuthra1 Can you please look into this issue?
