### ISSUE TITLE
Create the Menu Bar:

### ISSUE THREAD

**Issue by AveekBasu** [OpenPrinting/openprinting.github.io#8]
List: 

Home Page
Downloads
Tutorials
Project List
Blogs
Contact
Donation
News / Events
Driverless Printing

**Comment by dheeraj135** [comment]
Are you talking about this menu?
![screenshot from 2018-12-27 14-13-12](https://user-images.githubusercontent.com/28601604/50473125-baee9400-09e1-11e9-8d92-4b4a31363c29.png)

**Comment by AveekBasu** [comment]
Yes....

**Comment by dheeraj135** [comment]
I have added menu bar ,tutorials collection and reduced font size. You can check it here: https://dheeraj135.github.io/openprinting.github.io/

**Comment by sahilarora535** [comment]
@dheeraj135 Great work. However, the site has changed a bit, could you make the same changes according to the new source code? Thank you.

**Comment by dheeraj135** [comment]
Ok. I will work on this.

**Comment by dheeraj135** [comment]
@sahilarora535 Please check the changes here: https://dheeraj135.github.io/openprinting.github.io/ . Thanks.

**Comment by sahilarora535** [comment]
@dheeraj135 Great work. Just some small changes. Please remove **Contributing** and **Tutorial** from title bar, and the order of links should be:

1. About Us
2. News and Events
3. Blog
4. Projects
5. Downloads
6. Driverless Printing
7. Contact Us
8. Donate
