### ISSUE TITLE
Update OP Driverless Printing page for IPP Everywhere v1.1 release

### ISSUE THREAD

**Issue by iramcdonald** [OpenPrinting/openprinting.github.io#95]
The OP website Driverless Printing page at:
https://openprinting.github.io/driverless/01-standards-and-their-pdls/

...should be updated to note the release of IPP Everywhere™  v1.1 at:
https://ftp.pwg.org/pub/pwg/candidates/cs-ippeve11-20200515-5100.14.pdf
(which was released in May 2020 along with updated IPP Everywhere™ Self-Certification tools)

The Trademark symbol "™" should always be used with any mention of IPP
Everywhere™ since it's an international trademark of the PWG.

**Comment by michaelrsweet** [comment]
I opted to just add a link to the IPP Everywhere landing page. I also cleaned up the content...
